gui:
  # since 0.5x or so, new top level wrapper in file tree for '/', root of
  # project, which IDGI so go away plz kthxbai. NOTE: this config option was
  # added in 0.52.0.
  showRootItemInFileTree: false
  # branchColorPatterns?
  # customIcons?
  # scrollOffMargin?
  # scrollOffbehavior?
  # Ehhhh no thx
  mouseEvents: off
  scrollHeight: 10 # default 2
  timeFormat: "2006-01-02 @ 15:04 MST"
  #showIcons: true  # requires nerdfonts.com font in terminal
  showNumstatInFilesView: true
  sidePanelWidth: 0.4 # default 0.33(%)
git:
  # Really a gui setting...renders eg :rocket:
  parseEmoji: true
